name: Release Workflow

on: 
  release:
    types: [published, edited]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x' # Change this to the Go version you are using

      - name: Install dependencies
        run: go get .

      # - name: Build
      #   run: go build -v ./...

      - name: Run tests
        run: go test

  list:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'release' && needs.test.result == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.19' # Change this to the Go version you are using

      - name: Get release tag version
        run: |
          echo "Release tag: ${{ github.ref_name }}"
          GOPROXY=proxy.golang.org go list -m github.com/o-murphy/pystruct-go@${{ github.ref_name }}